import type { Metadata } from "next";
import { Hind } from "next/font/google";
import { type ReactElement, type ReactNode } from "react";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const poppinsFont = Hind({
  weight: ["300", "400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactElement {
  return (
    <html lang="en">
      <body
        className={twMerge(
          poppinsFont.className,
          "min-h-full bg-gradient-to-b from-blue-100 to-blue-300 bg-fixed text-slate-950/85",
        )}
      >
        {children}
      </body>
    </html>
  );
}
